### ISSUE TITLE
Update at least to v1.6

### ISSUE THREAD

**Issue by tomasmota** [upbound/provider-terraform#247] opened 2024-03-08 13:09 UTC
In version 1.5, import blocks must have literal strings in the id, meaning it is not possible to use variables to specify it. Since version 1.6 this is possible, and I would really like to use this feature.

Are there any plans of updating any time soon?

**Comment by jbw976** [comment] 2024-03-08 13:20
Thanks for your interest in this @tomasmota - unfortunately, there are no plans now to support greater than v1.5 due to the license change. A bit of discussion on this for reference:

https://github.com/upbound/provider-terraform/issues/227#issuecomment-1883253536 

I will close this issue as a duplicate of #227 ✅

**Closed by jbw976** 2024-03-08 13:20 UTC
Labels: enhancement, needs:triage

**Comment by tomasmota** [comment] 2024-03-08 13:23
fair enough, any progress on the plans with regards to updates/being able to use newer versions? Or opentofu I suppose

**Comment by jeanduplessis** [comment] 2024-03-08 13:38
@tomasmota there have been no further efforts put into exploring other options at this stage.

**Comment by brandonjbjelland** [comment] 2024-07-03 05:20
Curious - is this project considering adoption of opentofu?

**Comment by jeanduplessis** [comment] 2024-07-03 07:29
@brandonjbjelland We are waiting to see the outcome of https://github.com/cncf/sandbox/issues/81 before making a commitment on using OpenTofu. MPL-2.0 licensed code isn't part of the CNCF's current list of approved licenses and we are already trying to get exceptions for the existing use of MPL-2.0 code: https://github.com/cncf/foundation/issues/787 

Nothing stops a community member from creating a provider-opentofu though, in terms of this specific provider, we are not considering it right now.
