### ISSUE TITLE
aws cli as part of docker image

### ISSUE THREAD

**Issue by balu-ce** [upbound/provider-terraform#149] opened 2023-04-17 09:40 UTC
I am trying execute aws commands as execute null script resource but aws cli is not found . Can we had as part of docker build ?

**Comment by balu-ce** [comment] 2023-04-18 12:39
Since terraform provider is using alpine image as base, there is no option to install aws-cli as binary. so if its available as part of docker build I can use that

**Comment by svscheg** [comment] 2023-04-18 20:37
Hi @balu-ce ! Seems it is not a bug, more likely that it is a feature request/enhancement. 

According previous comment - the terraform AWS provider would be able to do everything that the CLI can do, and using provider-aws is the right thing to do instead of installing AWS CLI.

We are closing this issue as we do not plan to introduce the suggested enhancement to the project at this stage. You can reopen the issue with a comment if you would like to motivate why we should reconsider it.

**Closed** 2023-04-18 20:37 UTC
Labels: bug, needs:triage
